spring.application.name=claw-assistant

server.port=8080

# ????
logging.level.root=info
logging.level.com.claw=debug
logging.level.org.springframework=warn

# ????
logging.file.name=logs/app.log

# ?????
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(%-5level){highlight} %clr([%thread]){magenta} %clr(%logger{36}){cyan} - %clr(%msg%n){faint}

# ????
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n

aliyun.dashscope.api-key=
aliyun.dashscope.base-url=https://ws-ijj44d91a4u3un64.cn-beijing.maas.aliyuncs.com/compatible-mode/v1/chat/completions
aliyun.dashscope.model=qwen3.7-plus
aliyun.dashscope.vl-model=qwen-vl-plus
aliyun.dashscope.omni-model=qwen3.5-omni-plus